### ISSUE TITLE
comments inverted BuyVolume/BuyValue I suppose

### ISSUE THREAD

**Issue by LatinoMiner** [jufkes/bittrexBot#11]
https://github.com/jufkes/bittrexBot/blob/e37d0dfe347f3d44fe1662acd67d56e3c3d5447a/modules/buyUtil.py#L13

defBuyValue calculate the target price to pay
defBuyVolume calculate the number of coins to buy

**Comment by jufkes** [comment]
To avoid these kinds of issues from being created, i've removed all comments from the code.

Issues should be reserved for functional problems / feature requests / enhancements.
