### ISSUE TITLE
Please reload Volume quantity for each  loop

### ISSUE THREAD

**Issue by LatinoMiner** [jufkes/bittrexBot#12]

**Comment by jufkes** [comment]
Can you give me more detail? 
And why you want this since a volume set doesnt need to happen unless an order sets. Seems like an unnecessary call...

**Comment by LatinoMiner** [comment]
The idea is change the sell/buy percent during the execution of the bot. Just that.

**Comment by jufkes** [comment]
I still dont understand...are asking for on the fly config changes? 

If so, i do not plan to support that. The config file is read in at the start of the bot and would require more refactoring than I'd like / have time to do...day job and all...
