### ISSUE TITLE
Feature Request : Initial Sell Price

### ISSUE THREAD

**Issue by jufkes** [jufkes/bittrexBot#5]
A configuration that prevents the bot from placing any orders until an initial sell price has been met

See the notes on the buy price

**Comment by LatinoMiner** [comment]
Set the initial sell value in the config file and run the bot immediately.

**Comment by jufkes** [comment]
I added support for an initialSellPrice. The changes are in the 'sellPrice' branch. Feel free to give it a try. I'm currently unable to adequately test as I've got everything tied up in Strat at this given moment.

I also think i want to add a check as a fail safe so that you can never set a sell lower than the current market price

**Comment by jufkes** [comment]
Added a check to protect from setting a sell price that's under current market conditions.

**Comment by jufkes** [comment]
Testing looks good. The try / except block for 503 protection is also working.

Going to merge and close.
