### ISSUE TITLE
Catch 503's from Bittrex

### ISSUE THREAD

**Issue by jufkes** [jufkes/bittrexBot#9]
It would seem that bittrex's API's are flaky as hell. 

When the API's crap themselves, gracefully catch the failure and continue. This is probably going to amount to a shit ton of try-catch's...this does not make me happy so i'll have to research if there's a better way to handle this.

**Comment by LatinoMiner** [comment]
We need something like the --e option in bash commands

**Comment by jufkes** [comment]
I would think we'd want to do the opposite. -e would mean the app would exit whenever it receives something it doesnt expect, in this case the 503's. 

I'm going to encapsulate the calls to bittrex in try's to prevent crashing when bittrex is being a turd. As we get more and more volume hitting the API's its going to happen more often.

This way the app should hopefully restart less frequently. Restarting it rebases it's buy / sell markers which throws things out of whack as I'e observed the past couple days with ADX, MTL, and STRAT.

Its finding time to do so...

**Comment by LatinoMiner** [comment]
I'm interested to rewrite the bittrex.py for tradesatoshi
Your code is well done, should be easy add a config param to select the exchange

**Comment by jufkes** [comment]
Thanks! I'm hoping to add additional exchanges as time allows. I'm currently working on getting GDAX and Polo in there. 

BTW, I added a try / except inside the main loop that should account for 503's and pretty much every other condition. 
I'm going to compile and push it into docker tag v13...i'm not going to repin it to 'latest' until i can confirm it's not a turd pile.
